# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 40
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: cypress-io/github-action@v2
        with:
          node-version: "12"
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.8.1'
      - name: Run the install
        run: |
          meteor npm install --save
      - name: Run the production build
        run: |
          ./build.sh
      - name: Test docker image building
        run: |
          docker build .
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          test:  npm run cypress-io/github-action@v2
          wait-on: http://localhost:3030